local path = require('etc/fn/path')
local clipboard
clipboard = function()
  if vim.loop.os_uname().sysname == 'Darwin' then
    return {
      cache_enabled = 0,
      name = 'macOS-clipboard',
      copy = {
        ['+'] = 'pbcopy',
        ['*'] = 'pbcopy'
      },
      paste = {
        ['+'] = 'pbpaste',
        ['*'] = 'pbpaste'
      }
    }
  end
  return 'unnamedplus'
end
local options = {
  g = {
    loaded_2html_plugin = 1,
    loaded_getscript = 1,
    loaded_getscriptPlugin = 1,
    loaded_gzip = 1,
    loaded_logipat = 1,
    loaded_matchit = 1,
    loaded_netrw = 1,
    loaded_netrwFileHandlers = 1,
    loaded_netrwPlugin = 1,
    loaded_netrwSettings = 1,
    loaded_rrhelper = 1,
    loaded_spellfile_plugin = 1,
    loaded_tar = 1,
    loaded_tarPlugin = 1,
    loaded_vimball = 1,
    loaded_vimballPlugin = 1,
    loaded_zip = 1,
    loaded_zipPlugin = 1,
    did_load_filetypes = 1,
    mapleader = ' ',
    maplocalleader = [[\\]],
    zsh_fold_enable = 1,
    vimsyn_embed = 'lPr',
    clipboard = clipboard(),
    completion_matching_strategy_list = {
      'fuzzy',
      'subscring',
      'exact'
    },
    ts_highlight_lua = true,
    global_symbol_padding = '  ',
    markdown_fenced_languages = {
      'html',
      'python',
      'sh',
      'bash=sh',
      'javascript',
      'js=javascript',
      'json',
      'go',
      'typescript',
      'ts=typescript',
      'yaml',
      'yml=yaml'
    }
  },
  opt = {
    autoindent = false,
    autowriteall = true,
    backspace = {
      'indent',
      'eol',
      'start'
    },
    backup = false,
    backupskip = {
      '/tmp/*',
      '$TMPDIR/*',
      '$TMP/*',
      '$TEMP/*',
      '*/shm/*',
      '/private/var/*',
      '.vault.vim'
    },
    breakindentopt = {
      'shift:2',
      'min:20'
    },
    cindent = false,
    cmdheight = 1,
    colorcolumn = '+1',
    completeopt = 'menuone,noinsert,noselect',
    concealcursor = 'niv',
    conceallevel = 1,
    confirm = false,
    cursorline = false,
    diffopt = function(option)
      return option:append({
        'vertical',
        'iwhite',
        'hiddenoff',
        'foldcolumn:0',
        'context:1000000',
        'algorithm:histogram',
        'indent-heuristic'
      })
    end,
    equalalways = false,
    errorbells = false,
    expandtab = true,
    fillchars = function(option)
      return option:append({
        stl = ' ',
        stlnc = ' ',
        vert = '▕',
        fold = '⣿',
        eob = ' ',
        diff = '⣿',
        msgsep = '‾',
        foldopen = '▾',
        foldsep = '│',
        foldclose = '▸'
      })
    end,
    fileencoding = 'utf-8',
    fileformats = {
      'unix',
      'mac',
      'dos'
    },
    formatoptions = {
      ['1'] = true,
      ['2'] = false,
      a = false,
      c = true,
      j = true,
      l = true,
      n = true,
      o = true,
      q = true,
      r = true,
      t = false,
      v = false
    },
    hidden = true,
    hlsearch = true,
    ignorecase = true,
    jumpoptions = 'stack',
    keymodel = 'startsel,stopsel',
    linebreak = true,
    list = true,
    listchars = {
      space = '·',
      tab = '»·',
      trail = '·',
      eol = '↲'
    },
    magic = true,
    mouse = 'a',
    mousefocus = true,
    mousemodel = 'extend',
    mousetime = 500,
    number = true,
    numberwidth = 3,
    pumheight = 15,
    pumwidth = 20,
    redrawtime = 1500,
    relativenumber = false,
    ruler = false,
    scrolloff = 8,
    selection = 'inclusive',
    sessionoptions = {
      'globals',
      'buffers',
      'curdir',
      'help',
      'winpos'
    },
    shiftround = true,
    shiftwidth = 2,
    shortmess = {
      t = true,
      a = true,
      A = true,
      o = true,
      O = true,
      I = true,
      s = true,
      c = true,
      W = true,
      T = true,
      f = true,
      F = true
    },
    showcmd = true,
    showmode = false,
    showtabline = 0,
    sidescrolloff = 8,
    signcolumn = 'auto:1',
    smartcase = true,
    smartindent = true,
    smarttab = true,
    spell = false,
    spellcapcheck = '',
    spellfile = path.spellfile(),
    spelllang = 'en',
    spelloptions = 'camel',
    spellsuggest = function(option)
      return option:prepend({
        12
      })
    end,
    splitbelow = true,
    splitright = true,
    startofline = false,
    swapfile = false,
    switchbuf = 'useopen,uselast',
    synmaxcol = 2500,
    tabstop = 2,
    termguicolors = true,
    textwidth = 72,
    timeout = true,
    timeoutlen = 500,
    title = true,
    titlestring = '%<%F%=%l/%L - ',
    ttimeout = true,
    ttimeoutlen = 10,
    undofile = true,
    undolevels = 1000,
    updatetime = 100,
    viewdir = path.view(),
    viewoptions = {
      'cursor',
      'folds'
    },
    virtualedit = 'block,onemore',
    wildignore = {
      '*.hg',
      '*.svn',
      '*.aux',
      '*.out',
      '*.toc',
      '*.o',
      '*.obj',
      '*.dll',
      '*.jar',
      '*.pyc',
      '*.rbc',
      '*.class',
      '*.gif',
      '*.ico',
      '*.jpg',
      '*.jpeg',
      '*.png',
      '*.avi',
      '*.wav',
      '*.webm',
      '*.eot',
      '*.otf',
      '*.ttf',
      '*.woff',
      '*.doc',
      '*.pdf',
      '*.tar.gz',
      '*.tar.bz2',
      '*.rar',
      '*.tar.xz',
      '.sass-cache',
      '*/vendor/gems/*',
      '*/vendor/cache/*',
      '*/.bundle/*',
      '*.gem',
      '*.*~',
      '*~ ',
      '*.swp',
      '.lock',
      '*.DS_Stoe',
      '._*',
      'tags.lock',
      '**/node_modules/**',
      '**/bower_modules/**'
    },
    wrap = true,
    wrapscan = true,
    writebackup = false
  },
  o = {
    backup = false,
    completeopt = 'menuone,noinsert,noselect',
    errorbells = false,
    expandtab = true,
    hidden = true,
    incsearch = true,
    shiftwidth = 2,
    showmode = false,
    smartcase = true,
    softtabstop = -1,
    syntax = 'on',
    termguicolors = true,
    undodir = path.undo(),
    undofile = true
  },
  go = {
    backup = false,
    backupdir = path.backup(),
    cmdheight = 1,
    cmdwinheight = 2,
    completeopt = 'menuone,noinsert,noselect',
    directory = path.swap(),
    display = 'lastline,msgsep',
    emoji = true,
    equalalways = false,
    fileformats = 'unix,mac,dos',
    foldlevelstart = 10,
    grepprg = 'rg --hidden --vimgrep --smart-case --',
    hidden = true,
    history = 10000,
    hlsearch = true,
    ignorecase = true,
    inccommand = 'nosplit',
    incsearch = true,
    joinspaces = false,
    jumpoptions = 'stack',
    keymodel = 'startsel,stopsel',
    laststatus = 2,
    magic = true,
    mouse = 'a',
    mousefocus = true,
    mousemodel = 'extend',
    mousetime = 500,
    pumheight = 15,
    redrawtime = 1500,
    ruler = false,
    scrolloff = 5,
    selection = 'inclusive',
    shada = [[!,'300,<50,@100,s10,h]],
    shiftround = true,
    shortmess = 'Tfnwx',
    showcmd = true,
    showmode = false,
    showtabline = 1,
    smartcase = true,
    smarttab = true,
    splitbelow = true,
    splitright = true,
    startofline = false,
    switchbuf = 'useopen',
    timeout = true,
    timeoutlen = 500,
    ttimeout = true,
    ttimeoutlen = 10,
    undodir = path.undo(),
    updatetime = 300,
    viewdir = path.view(),
    virtualedit = 'block,onemore',
    whichwrap = 'h,l,<,>,[,],~',
    wildignorecase = true,
    wrapscan = true,
    writebackup = true
  },
  bo = {
    autoindent = true,
    cindent = false,
    expandtab = true,
    fileencoding = 'utf-8',
    formatoptions = '1jcroqlj',
    shiftwidth = 2,
    smartindent = true,
    softtabstop = -1,
    spellfile = path.spellfile(),
    spelllang = 'en',
    swapfile = false,
    synmaxcol = 2500,
    tabstop = 2,
    textwidth = 72,
    undolevels = 1000,
    undofile = true,
    showmode = false
  },
  wo = {
    breakindent = true,
    breakindentopt = 'shift:2,min:20',
    colorcolumn = '+1',
    concealcursor = 'niv',
    conceallevel = 0,
    cursorline = false,
    foldenable = true,
    list = true,
    number = true,
    numberwidth = 3,
    relativenumber = false,
    signcolumn = 'auto:1',
    scrolloff = 5,
    linebreak = true,
    wrap = false,
    virtualedit = 'block,onemore',
    showmode = false
  },
  t = {
    cmdheight = 1
  }
}
for ctx, values in pairs(options) do
  for option, value in pairs(values) do
    if value then
      if type(value) == 'function' then
        value(vim[ctx][option])
      else
        vim[ctx][option] = value
      end
    end
  end
end
