#############################################################
# Common packages among Brewfiles                           #
# $ brew bundle -v --file $HOME/.config/brew/Brewfile       #
# https://homebrew-file.readthedocs.io/en/latest/usage.html #
#############################################################

# taps
tap 'homebrew/bundle'

if `hostname`.strip == 'NCC1701'
  # languages
  brew 'go'

  # shells
  brew 'bash'

  # git
  brew 'git-secret'
  brew 'git-extras'

  # utilities
  brew 'gnupg'
  brew 'helix'
  brew 'hyperfine'
  brew 'coreutils'
  brew 'bat-extras'
  brew 'wakatime-cli'
  brew 'htop'
  brew 'task'
  brew 'taskwarrior-tui'
  brew 'hadolint'
  brew 'less'
  brew 'lesspipe'
  brew 'shellcheck'
end

if OS.mac?
  # options
  tap 'homebrew/cask'
  cask_args appdir: '~/Applications', require_sha: true

  # formulaes
  brew 'gopass'
  brew 'fontconfig'
  brew 'pinentry-mac'

  # apps
  cask 'vlc'
  cask 'kitty'
  cask 'discord'
  cask 'whatsapp'
  cask 'amazon-music'

  # browsers
  cask 'firefox'
  cask 'brave-browser'
  cask 'google-chrome'
  cask 'microsoft-edge'

  # fonts
  tap 'homebrew/cask-fonts'
  cask 'font-devicons'
  cask 'font-fira-code'
  cask 'font-cascadia-code'
  cask 'font-hack-nerd-font'
  cask 'font-powerline-symbols'
  cask 'font-fira-code-nerd-font'

  # utilities
  cask 'dash'
  cask 'atom'
  cask 'github'
  cask 'docker'
  cask 'insomnia'
  cask 'parallels'
  cask 'parallels-toolbox'
  cask 'jetbrains-toolbox'
  cask 'visual-studio-code'

  # productivity
  cask 'folx'
  cask 'alfred'
  cask 'dropbox'
  cask 'amethyst'
  cask 'grammarly'
  cask 'google-drive'
end
