---
creation_rules:
  - path_regex: .*secrets(\.encrypted)?\.yaml$
    age: age17q0hc40w3zukdw47zagn5f0rj72ggcu5ygxxpekpua6x3trp6q0syn9lt4
    encrypted_regex: '^(id|secret|bootstraptoken|secretboxencryptionsecret|token|ca|crt|key|value)$'
  - path_regex: .*\.env(\..*)?$
    age: age17q0hc40w3zukdw47zagn5f0rj72ggcu5ygxxpekpua6x3trp6q0syn9lt4
    encrypted_regex: '^.*_(SECRET|KEY|TOKEN|PASSWORD|PASS).*$'
