# The config file for mise
# https://mise.jdx.dev/configuration.html

# Dev Tools
# Manages dev tools like node, python, cmake, terraform, and hundreds more
# https://mise.jdx.dev/dev-tools
# [tools]
#   age       ="1.2.1"
#   sops      ="3.10.2"

# Tasks
# Like make, it manages tasks used to build and test projects
# https://mise.jdx.dev/tasks

# mise_bin: String - Points to the path to the current mise executable
# https://mise.jdx.dev/templates.html#variables
# https://mise.jdx.dev/cli/install.html#mise-install

# Tasks
# Like make, it manages tasks used to build and test projects
# https://mise.jdx.dev/tasks
[tasks] # mise run

  # mise run build --nocache
  # mise run build --nocache --runtime
  # mise run build --nocache --platform amd64 --tag latest
  # mise run build --nocache --runtime --distro debian --platform amd64 --tag latest --build-arg USERNAME=roalcantara --build-arg GROUPNAME=staff
  [tasks.build]
  description = "Build a Docker image for dotfiles"
  run = '''
  #!/usr/bin/env bash

  # Set defaults and parse options
  USAGE_PLATFORM="{{option(name="platform", default="arm64")}}"
  USAGE_SECRET_PATH="{{option(name="secret", default="./.secrets/github_token.secret")}}"
  USAGE_DISTRO="{{option(name="distro", default="debian")}}"
  USAGE_TAG="{{option(name="tag")}}"
  USAGE_BRANCH="{{option(name="branch")}}"
  USAGE_REPO="{{option(name="repo")}}"
  USAGE_USERNAME="{{option(name="user")}}"
  USAGE_GROUPNAME="{{option(name="group")}}"
  USAGE_BUILD_ARGS="{{option(name="build-arg", var=true)}}"
  DOCKERFILE_VALUE="Dockerfile"

  # Platform mapping
  case "$USAGE_PLATFORM" in
    amd64)    PLATFORM_VALUE="linux/amd64" ;;
    arm64)    PLATFORM_VALUE="linux/arm64" ;;
    amd64v2)  PLATFORM_VALUE="linux/amd64/v2" ;;
    riscv64)  PLATFORM_VALUE="linux/riscv64" ;;
    ppc64le)  PLATFORM_VALUE="linux/ppc64le" ;;
    s390x)    PLATFORM_VALUE="linux/s390x" ;;
    386)      PLATFORM_VALUE="linux/386" ;;
    *)        PLATFORM_VALUE="linux/arm64" ;;
  esac

  # Distro mapping
  case "$USAGE_DISTRO" in
    debian)   DISTRO_NAME="bookworm" ;;
    *)        DISTRO_NAME="bookworm" ;;
  esac

  # Compose docker build command
  DOCKER_CMD=(
    DOCKER_BUILDKIT=1 docker build
    --build-arg=BUILDKIT_INLINE_CACHE=1
  )

  if [ -n "$USAGE_USERNAME" ]; then
    DOCKER_CMD+=(--build-arg=USERNAME="$USAGE_USERNAME")
  fi

  if [ -n "$USAGE_GROUPNAME" ]; then
    DOCKER_CMD+=(--build-arg=GROUPNAME="$USAGE_GROUPNAME")
  fi

  if [ -n "$USAGE_BRANCH" ]; then
    DOCKER_CMD+=(--build-arg=BRANCH="$USAGE_BRANCH")
  fi

  if [ -n "$USAGE_REPO" ]; then
    DOCKER_CMD+=(--build-arg=GITHUB_REPO="$USAGE_REPO")
  fi

  # Add extra build-args if any
  for arg in $USAGE_BUILD_ARGS; do
    DOCKER_CMD+=(--build-arg="$arg")
  done

  # Add secret if available
  if [[ -z $GITHUB_TOKEN && -f $USAGE_SECRET_PATH ]]; then
    DOCKER_CMD+=(--secret="id=github_token,src=$USAGE_SECRET_PATH")
  fi

  if [ -n "$PLATFORM_VALUE" ]; then
    DOCKER_CMD+=(--platform="$PLATFORM_VALUE")
  fi

  # Compose tag
  TAG_VALUE="dots:$USAGE_DISTRO-$USAGE_PLATFORM"
  [ -n "$USAGE_TAG" ] && TAG_VALUE="$TAG_VALUE-$USAGE_TAG"
  DOCKER_CMD+=(--tag="$TAG_VALUE")

  # Add --no-cache if requested
  if [ "{{flag(name="nocache")}}" = "true" ]; then
    DOCKER_CMD+=(--no-cache)
  fi

  # Select Dockerfile
  if [ '{{flag(name="runtime")}}' = 'true' ]; then
    DOCKERFILE_VALUE="Dockerfile.runtime"
  fi
  DOCKER_CMD+=(--file="distros/$USAGE_DISTRO/$DOCKERFILE_VALUE" .)

  echo "  ==> ${DOCKER_CMD[*]}"
  eval "${DOCKER_CMD[*]}"
  '''

  # mise run start
  # mise run start --base
  # mise run start --tag local
  # mise run start --tag local --platform amd64
  # mise run start --tag local --user root --workdir /workspaces/foo
  [tasks.start]
  description = "Start a container"
  run = '''
  #!/usr/bin/env bash

  # Set defaults and parse options
  USAGE_PLATFORM="{{option(name="platform", default="arm64")}}"
  USAGE_DISTRO="{{option(name="distro", default="debian")}}"
  USAGE_TAG="{{option(name="tag")}}"
  USAGE_USER="{{option(name="user", default="vscode")}}"
  USAGE_WORKDIR="{{option(name="workdir", default="/workspaces/dots")}}"

  # Distro mapping
  case "$USAGE_DISTRO" in
    debian)   DISTRO_NAME="bookworm" ;;
    *)        DISTRO_NAME="bookworm" ;;
  esac

  DOCKER_CMD=(
    docker run -it --tty --rm
    --user="$USAGE_USER"
    --workdir="$USAGE_WORKDIR"
  )

  if [ -z "$USAGE_TAG" ]; then
    DOCKER_CMD+=(--entrypoint='zsh' mcr.microsoft.com/devcontainers/ruby:3.4-$DISTRO_NAME)
  else
    DOCKER_CMD+=(dots:$USAGE_DISTRO-$USAGE_PLATFORM-$USAGE_TAG)
  fi

  echo "  ==> ${DOCKER_CMD[*]}"
  eval "${DOCKER_CMD[*]}"
  '''



  # mise run test
  # mise run test --image dots:debian-arm64-dev
  # mise run test --image dots:debian-amd64-latest --config distros/debian/container-structure-test.yml
  [tasks.test]
  description = "Run the Container Structure Tests for the Docker image"
  run = '''
  #!/usr/bin/env bash

  # Set defaults and parse options
  USAGE_PLATFORM="{{option(name="platform", default="arm64")}}"
  USAGE_DISTRO="{{option(name="distro", default="debian")}}"
  USAGE_TAG="{{option(name="tag", default="dev")}}"
  USAGE_USER="{{option(name="user", default="vscode")}}"
  USAGE_WORKDIR="{{option(name="workdir", default="/workspaces/dots")}}"

  # Platform mapping
  case "$USAGE_PLATFORM" in
    amd64)    PLATFORM_VALUE="linux/amd64" ;;
    arm64)    PLATFORM_VALUE="linux/arm64" ;;
    amd64v2)  PLATFORM_VALUE="linux/amd64/v2" ;;
    riscv64)  PLATFORM_VALUE="linux/riscv64" ;;
    ppc64le)  PLATFORM_VALUE="linux/ppc64le" ;;
    s390x)    PLATFORM_VALUE="linux/s390x" ;;
    386)      PLATFORM_VALUE="linux/386" ;;
    *)        PLATFORM_VALUE="linux/arm64" ;;
  esac

  # Distro mapping
  case "$USAGE_DISTRO" in
    debian)   DISTRO_NAME="bookworm" ;;
    *)        DISTRO_NAME="bookworm" ;;
  esac

  DOCKER_CMD=(
    docker run -it --tty --rm
    --user="$USAGE_USER"
    --workdir="$USAGE_WORKDIR"
  )

  if [ "{{flag(name="base")}}" = "true" ]; then
    DOCKER_CMD+=(mcr.microsoft.com/devcontainers/ruby:3.4-$DISTRO_NAME)
  else
    DOCKER_CMD+=(dots:$USAGE_DISTRO-$USAGE_PLATFORM-$USAGE_TAG)
  fi

  echo "  ==> ${DOCKER_CMD[*]}"
  eval "${DOCKER_CMD[*]}"

  # Set defaults and parse options
  USAGE_IMAGE="{{option(name="image", default="dots:debian-arm64-dev")}}"
  USAGE_CONFIG="{{option(name="config", default="distros/debian/container-structure-test.yml")}}"

  # Run container-structure-test
  container-structure-test test --image "$USAGE_IMAGE" --config "$USAGE_CONFIG"
  '''

# Settings
# https://mise.jdx.dev/configuration/settings.html#settings
[settings]
  # Pushes tools' bin-paths to the front of PATH instead of allowing modifications of PATH after activation to take precedence.
  # https://mise.jdx.dev/configuration/settings.html#activate_aggressive
  activate_aggressive=true

  # Automatically install missing tools when running mise x, mise run, or as part of the 'not found' handler.
  # https://mise.jdx.dev/configuration/settings.html#auto_install
  auto_install=true

  # set to true to enable experimental features
  # https://mise.jdx.dev/configuration/settings.html#experimental
  experimental=true

  # Config files with these prefixes will be trusted by default
  # https://mise.jdx.dev/configuration/settings.html#global_config_file
  global_config_file="~/.local/share/mise/config.toml"

  # Specific tools to enable idiomatic version files for like .node-version, .ruby-version, etc.
  # https://mise.jdx.dev/configuration/settings.html#idiomatic_version_file_enable_tools
  idiomatic_version_file_enable_tools=["go", "node", "python", "ruby", "yarn"]

  # Read/update lockfiles for tool versions. This is useful when you'd like to have loose versions in mise.tomlLockfile to use for the project.
  # https://mise.jdx.dev/configuration/settings.html#lockfile
  lockfile=true

  # Change output style when executing tasks. This controls the output of mise run.
  # https://mise.jdx.dev/configuration/settings.html#task_output
  task_output="interleave"

  # Automatically install tools that are not installed when running tasks
  # https://mise.jdx.dev/configuration/settings.html#task_run_auto_install
  task_run_auto_install=true

  # Config files with these prefixes will be trusted by default
  # https://mise.jdx.dev/configuration/settings.html#trusted_config_paths
  trusted_config_paths=["~/.local/share/dots", "~/.local/share/mise"]

  # set to true to automatically answer yes to all prompts
  # https://mise.jdx.dev/configuration/settings.html#yes
  yes=true

  # set to true to see full installation output, see `MISE_VERBOSE`
  # https://mise.jdx.dev/configuration/settings.html#verbose
  # verbose=true
