# syntax=docker/dockerfile:1.7

# https://mcr.microsoft.com/en-us/artifact/mar/devcontainers/ruby/tags
FROM mcr.microsoft.com/devcontainers/ruby:3.4-bookworm

# Set build arguments and environment variables
ARG TZ=America/Sao_Paulo
ARG TERM=xterm-256color
ARG BRANCH=main
ARG USERNAME=vscode
ARG GROUPNAME=vscode
ARG GITHUB_REPO_NAME=dots
ARG GITHUB_REPO=roalcantara/dots

ENV CLICOLOR=1 \
    TZ=$TZ \
    TERM="$TERM" \
    COLORTERM=truecolor \
    DEBIAN_FRONTEND=noninteractive \
    USER="$USERNAME" \
    GROUP="$GROUPNAME" \
    HOME="/home/$USERNAME" \
    GOPATH="/home/$USERNAME/.local/share/go"

# Copy configuration files
WORKDIR "/home/$USERNAME/.local/share/dots"

# Copy the entire dots directory into the container
COPY ../../. "/home/$USERNAME/.local/share/dots/"

# Execute the install script during build
RUN --mount=type=secret,id=github_token,target=/tmp/github_token,required=false \
    --mount=type=cache,target=$HOME/.cache,uid=1000,gid=1000 \
    chown -R "$USERNAME:$GROUPNAME" "/home/$USERNAME/.local" && \
    chmod +x "/home/$USERNAME/.local/share/dots/install" && \
    chown "$USERNAME:$GROUPNAME" "/home/$USERNAME/.local/share/dots/install" && \
    # Remove .git directory to prevent the install script from trying to pull from GitHub
    rm -rf "/home/$USERNAME/.local/share/dots/.git" && \
    # Execute the install script during build
    "/home/$USERNAME/.local/share/dots/install" -u "${USERNAME}" -g "${GROUPNAME}" -t "${TZ}"

# Switch to vscode user
USER $USERNAME
WORKDIR $HOME
SHELL ["/usr/bin/zsh", "-c"]
ENTRYPOINT ["/usr/bin/zsh", "-il"]
