cheats:
  Arquiteto de soluções:
    desc: Job description
    tags: [job, arquiteto]
    notes: |
      ## Arquiteto de soluções

      ### Conhecimento necessário:

      - Profundo entendimento de arquiteturas de sistemas, incluindo microserviços, APIs, serviços web e cloud computing (AWS, Azure, Google Cloud).

      - Experiência com contêineres e orquestração de contêineres (Docker, Kubernetes).

      - Conhecimentos em segurança de aplicações, padrões de design, princípios SOLID e padrões de arquitetura de software.

      - Habilidades de Programação: Proficiência em várias linguagens de programação, como Java, Python, .NET, ou Node.js.

      ### Diferenciais:

      - Certificações profissionais em arquitetura de soluções (AWS Certified Solutions Architect, Google Cloud Architect, Microsoft Certified: Azure Solutions Architect Expert) são altamente desejáveis.

      - Experiência em Liderança Técnica:

      - Experiência em liderar equipes de desenvolvimento e arquitetura em projetos de TI, demonstrando habilidades de liderança e mentorship.

      - Conhecimento em IA e Machine Learning:

      - Familiaridade com conceitos de inteligência artificial e machine learning e sua aplicação em soluções empresariais.

      - Experiência Internacional:

      - Experiência com projetos globais ou em ambientes multiculturais pode ser um diferencial.

      - Inovação e Pesquisa: Contribuições para projetos de código aberto, publicações ou patentes na área de tecnologia.

  System Architect - Operations and 3rd party:
    desc: System Architect - Operations and 3rd party
    tags: [job, arquiteto]
    notes: |

      ## System Architect - Operations and 3rd party
      Malmö, Skane County, Sweden

      Verisure Innovation in Malmö is Sweden’s award-winning innovation center for the connected & protected smart-home market. We create services and IoT products for smarter, safer and more secure homes, serving customers throughout Northern Europe. We are now looking for our next IT System Architect, are you ready for your next challenge?

      About the role

      As an IT System Architect at Verisure you will hold an important role in defining the mid-term plan and strategy and align it with the company strategy. You will also perform discovery and analysis for new initiatives. You are responsible for gathering requirements for new systems prior to implementation. In this role you will be the system architect for an enablement team, focusing on operations and 3rd party, and work very close to the development teams in the Business Applications department. The team is securing lifecycle, growth and scaling for 50 services on around 100 servers, across different sites and environments. You will represent the team in different forums to find the best solutions to our company’s challenges.



      Some of the projects the team is working on right now:

      Lifecycle activities (OS/Middleware Patch, EOL upgrade, Vulnerability remediation, etc.)

      Microservice release and devops transformation support

      3rd party service integration

      What you bring

      You are a curious person who thrives in a complex role where you get to have a helicopter view of everything regarding your department. We believe you are a structured person and apply agile methodologies to your work. You have excellent communication and interpersonal skills, with the ability to collaborate effectively with cross-functional teams and stakeholders.

      You also have:

      Proven experience as a System Architect or a similar role

      Experience in Kubernetes, Jira/Confluence and Ansible.

      Deep understanding of infrastructure systems and willingness to learn new technologies, including 3rd party software

      Strong analytical and problem-solving skills with the ability to assess complex IT systems and propose effective solutions

      You are fluent in English, both written and spoken



      It’s merited if you have experience in:

      Nagios/Icinga/OMD, (server operations)

      Azure, Terraform (cloud computing)

      Docker, Grafana, Prometheus, ArgoCD,  (microservice related)

      What we offer
      Verisure is a global leading provider of professionally monitored security solutions. We are an international company with a start-up mindset, fast, agile, and lean, high-performance and value driven. We protect more than four million customers in 16 countries. Our business model integrates product development, design and sales with installation, outstanding service and a 24/7 professional monitoring solution. We protect people from intrusion, fire, and flood - and we save lives.

      Over the past years, Verisure has experienced an exceptional and resilient financial performance with a very long track record of double-digit growth - thanks to continuous drive for Innovation, our very sophisticated Go-To-Market approach and replicable business model for expansion into new countries. We are now supporting the business’ next phase of growth with a robust business plan for value creation. Verisure’s success depends on its people, and we invest in them every day. Working with Verisure is being part of an industry leading world-class company that has a strong entrepreneurial spirit.

      Are you interested in becoming part of Verisure? Apply today!

      We are excited to hear from you! Send your application already today. If you have questions regarding this position reach out to our Global TA Specialist, Lucas Stenberg at lucas.stenberg@verisure.com


      Interested in learning more about us? Get inspired by our colleagues talking about how it feels to be part of our exciting journey by clicking here https://www.youtube.com/watch?v=pjDxUndJf98
