# order
# ⌃ ⌥ ⇧ ⌘ A..
# ~/.config/cheat/pv/local/shortcuts/shortcuts-general
# ~/.config/cheat/yml/macos.yml
# ~/Work/raycast/symbl/assets/unicodes.yaml
shortcuts:
  zsh:
    ⌥ c:
      desc: Fuzzy find directory
      tags: [search, file, fzf]
    ⌃ r:
      desc: Reverse search history
      tags: [search, history, fzf]
    ⌃ t:
      desc: Fuzzy find file
      tags: [search, file, fzf]
    ⌥ f:
      desc: Move cursor to next word (forward)
      tags: [navigation]
    ⌥ b:
      desc: Move cursor to previous word (backwards)
      tags: [navigation]
    ⌃ xx:
      desc: Toggle between the start of the line and the current cursor position
      tags: [navigation]
    ⌃ x,e:
      desc: Open the current command line in your default editor
      tags: [editing, command]
    ⌃ k:
      desc: Cut (delete) text from the current cursor position until the end of the line
      tags: [editing, delete]
    ⌃ u:
      desc: delete whole line
      tags: [editing, delete]
    ⌥ w:
      desc: Delete text from the current cursor position to the beginning of the word
      tags: [editing, delete]
    ⌥ l:
      desc: Lowercase word
      tags: [editing, transform]
    ⌥ u:
      desc: Uppercase word
      tags: [editing, transform]
    ⌃ w:
      desc: Cut the previous word, starting from the current cursor position
      tags: [editing, delete]
    ⌥ ⌫:
      desc: Delete previous word, preceding the current cursor position
      tags: [editing, delete]
    ⌥ d:
      desc: delete next word, following the current cursor position
      tags: [editing, delete]
    ⌥ .:
      desc: Previous command's last argument
      tags: [history, command, terminal]
    \!$:
      desc: retrieves the last argument from the previous command
      tags: [history, command, terminal]
    \!*:
      desc: retrieves all arguments from the previous command
      tags: [history, command, terminal]
    ⌥ t:
      desc: Swap the last two characters before the cursor (typo)
      tags: [editing, text]
    ⌥ r:
      desc: Undo all changes made to the current command line
      tags: [editing, undo, terminal]
    ⌃ l:
      desc: Clear screen
      tags: [terminal, ui]
    ⌃ c:
      desc: Send an Interrupt/Kill signal to the currently running command
      tags: [process, terminal, control]
    ⌃ d:
      desc: Close Current Shell
      tags: [terminal, process, control]
    ⌃ z:
      desc: Suspends the currently running foreground job and moves it to the background
      tags: [process, terminal, control]
    fg:
      desc: Bring the most recent background job to the foreground
      tags: [process, terminal, control]
    ⌃ s:
      desc: Retrieves the next most recent command from your history
      tags: [history, command, terminal]
    ^abc^def:
      desc: Replaces the first occurrence of "abc" in the previous command with "def"
      tags: [history, command, substitution]
    ⌃ x,v:
      desc: Switch to vi mode in Zsh
      tags: [vi-mode, terminal]
    set -o vi:
      desc: Enables the vi mode for the current session
      tags: [vi-mode, terminal]
    cd ↵:
      desc: Go to HOME
      tags: [navigation, directory]
    cd ⇥:
      desc: Fuzzy find directory
      tags: [search, directory, fzf]
  vi:
    ⌘ p:
      desc: Search files by name
      tags: [search, file, navigation]
    ⇧ ⌘ p:
      desc: Show command palette
      tags: [command, ui, palette]
    ⌘ \:
      desc: Toggle left side bar
      tags: [ui, view, sidebar]
    ⌥ ⌘ ←:
      desc: Move to buffer at left
      tags: [navigation, buffer, window]
    ⌥ ⌘ →:
      desc: Move to buffer at right
      tags: [navigation, buffer, window]
    ⌘ a:
      desc: Select All
      tags: [selection, text]
    ⌘ n:
      desc: New File
      tags: [file, create]
    ⌘ ↑:
      desc: Go to the top of the file
      tags: [navigation, file]
    ⌘ ↓:
      desc: Go to the bottom of the file
      tags: [navigation, file]
    ⌃ a:
      desc: Move to beginning of line
      tags: [navigation]
    ⌃ e:
      desc: Move to end of line
      tags: [navigation]
    ⌘ x:
      desc: Cut selection to clipboard
      tags: [editing, clipboard, text]
    ⌘ c:
      desc: Copy selection to clipboard
      tags: [editing, clipboard, text]
    ⌘ v:
      desc: Paste the contents from Clipboard
      tags: [editing, clipboard, text]
    ⌘ z:
      desc: Undo the previous command
      tags: [editing, undo]
    ⌘ y:
      desc: Redo the previous command
      tags: [editing, redo]
    ⌥ ↓:
      desc: Move Line Down
      tags: [editing, move]
    ⌥ ↑:
      desc: Move Line Up
      tags: [editing, move]
    ⌘ ←:
      desc: Move to BOL
      tags: [navigation]
    ⌘ →:
      desc: Move to EOL
      tags: [navigation]
    ⌘ f:
      desc: Find in files
      tags: [search, file]
    ⌘ ⇧ f:
      desc: Find in project
      tags: [search, project]
    ⌘ .:
      desc: Code actions
      tags: [lsp, code, action]
    ⌘ d:
      desc: Toggle Diagnostics
      tags: [lsp, diagnostics, ui]
    ⇧ ⌘ e:
      desc: Toggle Errors
      tags: [lsp, diagnostics, ui]
    ⌘ i:
      desc: Go to Definition
      tags: [lsp, navigation, code]
    ⌘ ⌥ i:
      desc: Go to Implementation
      tags: [lsp, navigation, code]
    ⌘ ⌥ d:
      desc: Go to Declaration
      tags: [lsp, navigation, code]
    ⌘ ⌥ t:
      desc: Go to Type Definition
      tags: [lsp, navigation, code]
    ⌘ ⌥ w:
      desc: Go to Workspace Symbols
      tags: [lsp, navigation, symbol]
    ⌘ T:
      desc: Go to Symbol in File
      tags: [lsp, navigation, symbol]
    ⌘ ⇧ K:
      desc: Show Hover Information
      tags: [lsp, info, ui]
    ⌘ ⇧ ␣:
      desc: Trigger Parameter Hints
      tags: [lsp, hint, ui]
    ⌘ ⌥ r:
      desc: Find References
      tags: [lsp, search, code]
    ⌘ ⌥ ↵:
      desc: Rename Symbol
      tags: [lsp, editing, code]
    ⌘ ⌃ f:
      desc: Format Document
      tags: [editing, format, code]
    ⌘ ⇧ ]:
      desc: Next Diagnostic
      tags: [lsp, navigation, diagnostics]
    ⌘ ⇧ [:
      desc: Previous Diagnostic
      tags: [lsp, navigation, diagnostics]
    ⌘ [:
      desc: Fold
      tags: [view, folding, code]
    ⌥ ⌘ [:
      desc: Fold All
      tags: [view, folding, code]
    ⌘ ]:
      desc: Unfold
      tags: [view, folding, code]
    ⌥ ⌘ ]:
      desc: Unfold All
      tags: [view, folding, code]
    ⌘ /:
      desc: Toggle comment line
      tags: [editing, comment, code]
    ⌘ w:
      desc: Close Editor
      tags: [window, ui]
  code:
    ⌥ m:
      desc: Toggle Main Menu
      tags: [ui, menu]
    ⇧ ⌘ p:
      desc: Show command palette
      tags: [command, ui, palette]
    ⌘ \:
      desc: Toggle left side bar
      tags: [ui, view, sidebar]
    ⌥ ⌘ ←:
      desc: Go to tab at left
      tags: [navigation, tab, window]
    ⌥ ⌘ →:
      desc: Go to tab at right
      tags: [navigation, tab, window]
    ⌘ p:
      desc: Search files by name
      tags: [search, file, navigation]
    ⌘ a:
      desc: Select all
      tags: [selection, text]
    ⌘ n:
      desc: New File
      tags: [file, create]
    ⌘ ↑:
      desc: Go to the top of the file
      tags: [navigation, file]
    ⌘ ↓:
      desc: Go to the bottom of the file
      tags: [navigation, file]
    ⌃ a:
      desc: Move to beginning of line
      tags: [navigation]
    ⌃ e:
      desc: Move to end of line
      tags: [navigation]
    ⌘ x:
      desc: Cut selection to clipboard
      tags: [editing, clipboard, text]
    ⌘ c:
      desc: Copy selection to clipboard
      tags: [editing, clipboard, text]
    ⌘ v:
      desc: Paste
      tags: [editing, clipboard, text]
    ⌘ z:
      desc: Undo
      tags: [editing, undo]
    ⌘ y:
      desc: Redo
      tags: [editing, redo]
    ⌥ ↓:
      desc: Move Line Down
      tags: [editing, move]
    ⌥ ↑:
      desc: Move Line Up
      tags: [editing, move]
    ⌘ ←:
      desc: Move to BOL
      tags: [navigation]
    ⌘ →:
      desc: Move to EOL
      tags: [navigation]
    ⌘ f:
      desc: Find in files
      tags: [search, file]
    ⌘ ⇧ f:
      desc: Search in files
      tags: [search, file]
    ⌘ .:
      desc: Code actions
      tags: [lsp, code, action]
    ⌘ d:
      desc: Toggle Problems
      tags: [lsp, diagnostics, ui]
    ⌘ i:
      desc: Go to Definition
      tags: [lsp, navigation, code]
    ⌘ ⌥ i:
      desc: Go to Implementation
      tags: [lsp, navigation, code]
    ⌘ ⌥ d:
      desc: Go to Declaration
      tags: [lsp, navigation, code]
    ⌘ ⌥ t:
      desc: Go to Type Definition
      tags: [lsp, navigation, code]
    ⌘ ⌥ w:
      desc: Go to Workspace Symbols
      tags: [lsp, navigation, symbol]
    ⌘ T:
      desc: Go to Symbol in File
      tags: [lsp, navigation, symbol]
    ⌘ ⇧ K:
      desc: Show Hover Information
      tags: [lsp, info, ui]
    ⌘ ⇧ ␣:
      desc: Trigger Parameter Hints
      tags: [lsp, hint, ui]
    ⌘ ⌥ r:
      desc: Find References
      tags: [lsp, search, code]
    ⌘ ⌥ ↵:
      desc: Rename Symbol
      tags: [lsp, editing, code]
    ⌘ ⌃ f:
      desc: Format Document
      tags: [editing, format, code]
    ⌘ ⇧ ]:
      desc: Next Diagnostic Problem
      tags: [lsp, navigation, diagnostics]
    ⌘ ⇧ [:
      desc: Previous Diagnostic Problem
      tags: [lsp, navigation, diagnostics]
    ⌘ [:
      desc: Fold
      tags: [view, folding, code]
    ⌥ ⌘ [:
      desc: Fold All
      tags: [view, folding, code]
    ⌘ ]:
      desc: Unfold
      tags: [view, folding, code]
    ⌥ ⌘ ]:
      desc: Unfold All
      tags: [view, folding, code]
    ⌘ ⌃ g:
      desc: Replace All Occurrences
      tags: [editing, search, text]
    ⌘ ⌃ i:
      desc: Copilot | Inline Chat
      tags: [ai, assistant, code]
    ⌘ ⌃ z:
      desc: Toggle Zen Mode
      tags: [view, ui, zen]
    ⌘ /:
      desc: Toggle comment line
      tags: [editing, comment, code]
    ⌘ w:
      desc: Close Editor
      tags: [window, ui]
  wezterm:
    ⌥ m:
      desc: Toggle Main Menu
      tags: [ui, menu]
    ⌘ w:
      desc: Close Tab
      tags: [window, tab]
    ✦ r_⌘ ⌥ 1:
      desc: Switch to Tab 1
      tags: [navigation, tab]
    ✦ r_⌘ ⌥ 2:
      desc: Switch to Tab 2
      tags: [navigation, tab]
    ✦ r_⌘ ⌥ T:
      desc: New Tab
      tags: [tab, create]
    ✦ r_⌘ ⌥ →:
      desc: Next Tab
      tags: [navigation, tab]
    ✦ r_⌘ ⌥ ←:
      desc: Previous Tab
      tags: [navigation, tab]
    ✦ r_⌘ ↑:
      desc: Split Panel Up
      tags: [panel, layout]
    ✦ r_⌘ ↓:
      desc: Split Panel Down
      tags: [panel, layout]
    ✦ r_⌘ →:
      desc: Split Panel Right
      tags: [panel, layout]
    ✦ r_⌘ ←:
      desc: Split Panel Left
      tags: [panel, layout]
    ✦ p:
      desc: Open Command Palette
      tags: [command, palette, ui]
