cheats:
  LinkedIn recommendations:
    desc: Simple 5 step formula for a LinkedIn recommendation
    tags: [linkedin, recommendation, career]
    notes:
      - md: |

          ## Simple 5 step formula for a LinkedIn recommendation:

          1. Start with how long you've known/worked with the person
          2. Explain the context of the relationship
          3. Emphasize a couple of professional skills the person is good at (or results for projects they've worked on)
          4. Describe who they are on a personal level
          5. Conclude with a call to action

          ### 1. Example for a work colleague you managed

          "I've worked with Sally for over 5 years.
          I first met Sally when she was hired onto the marketing team as a coordinator, since then she has been promoted several times.
          Sally has some of the top marketing skills needed to help organizations stand out in an increasingly noisy environment.
          She led the team's branding, marketing and communications successfully. (Give specific examples if you have them - increased by X amount, etc.)
          What I really enjoy about Sally is her ability to bring people together, she is a true professional and team player and I would highly recommend her for any role."

          ### 2. Example for a work colleague from another team

          “I have enjoyed working with Sam for the last year.
          Our teams worked closely together to help build out the company's project management process.
          I found him to be hard-working, bright, and a skilled communicator.
          I particularly enjoyed his sense of humor in the face of what can sometimes be a stressful situation when faced with tight deadlines.
          But what makes him stand out is his willingness to help others.
          I am glad to have worked with him and have no hesitation recommending him to potential employers.”

          ### 3. Example for a manager

          "Jane was my manager for over 3 years.
          I very much enjoyed working with her on many projects throughout her tenure.
          She led the team to consistently exceed quote month over month.
          She sets realistic goals and gives clear instructions and feedback.
          She instills pride, confidence, and positive energy in everyone on her team.
          I would welcome the opportunity to work with her again.
          If you have the chance to work with Jane, take it!"

          ### 4. Example for a client

          “My company was brought in by Tina 3 years ago to help them implement a new marketing software platform.
          I found her to be highly cooperative and responsive.
          She set the strategy, handled the project timeline and was extremely valuable to both us as a vendor and her organization in getting to a successful outcome.
          I found her to be amenable, adaptable and witnessed her interaction with her team and was impressed with those as well.
          I look forward to working with her again in the future and highly recommend her for any role.”

  Lead Software Engineer/Solution Architect | LinkedIn recommendation:
    desc: A LinkedIn recommendation for a Lead Software Engineer/Solution Architect
    tags: [linkedin, recommendation, career]
    notes:
      - md: |
          ## 1. Template for a Solution Architect

          "It's rare that you come across standout talent like [Name].
          I had the pleasure of working alongside [him/her/them] for [duration] on [project or type of projects].
          [Name]'s ability to handle complex architectural challenges was unlike any I've seen before and made a dramatic increase in the productivity level of our team.
          [He/she/they] has my highest recommendation."

          ## 2. Template for a Lead Software Engineer

          "[Name] is a phenomenal leader and engineer.
          During our time together, [Name] managed the [specific task or project], demonstrating not just technical expertise but also a keen ability to manage both people and deadlines.
          The success of the [project name] project is a testament to [his/her/their] skills and effort."

          ## 3. Template for a Solution Architect:

          "I had the opportunity to work with [Name] for several years at [Company], where [he/she/they] took on roles that required both keen technical expertise and architectural foresight.
          [Name]'s solutions were always designed with scalability and efficiency in mind, which significantly benefited our operations."

          ## 4. Template for a Lead Software Engineer

          "As a lead engineer, [Name] has not only shown technical brilliance but has also mentored many young developers, including myself.
          [His/her/their] approach to coding and problem-solving has greatly influenced my own development.
          [Name] is a reliable and insightful leader, well-deserving of any accolades."

          ### 5. Template for a Solution Architect:

          "[Name] excels in roles that require strategic thought and a deep understanding of technology.
          [He/she/they] played a pivotal role in [specific project], where [his/her/their] architectural designs were critical to our success.
          I am continuously impressed by [Name]'s innovation and attention to detail."
      - md: |
          ### 1. Example for a Solution Architect

          [NAME] is a highly qualified professional, always ready for any challenge.
          He was always helpful and proactive.
          I can only say positive things about his personality.
          Highly recommended.

          ### 2. Example for a Solution Architect

          It is rare to find such a talented professional as [NAME], who had immense desire to work and learn from him.
          Possessing an immense technical capacity and empathy with the team to which I am inserted, He was able to solve architectural problems and still lead me in various moments of the project where we work together.
          I recommend this professional for excellent work and empathy with the entire team.

          ### 3. Example for a Solution Architect

          [NAME] is a focused professional, resilient and worried to achieve the deadlines,
          proposing solutions that better fit to the case, trying to strike a balance
          between the client's expectations and the sustainability of the project.
          I had worked some years with him and we frequently discussed and shared experiences that
          usually helped in the projects we were working, even if we had worked at the same company
          but in different projects and teams.

          ### 4. Example for a Solution Architect

          Bom profissional! Correto com que fez, trabalha com seriedade, lealdade e compromisso.

          ### 5. Example for a Solution Architect

          [NAME] conseguiu grandes resultados no desenvolvimento de soluções em .Net.
          De fácil relação com a equipe e superiores, sempre se mostrou muito pró-ativo e comprometido com o resultado.
          Alta qualidade de código desenvolvido conciliado com um ótimo desempenho produtivo,
          mostrando expertise necessária para atuar em pequenos, médios e grandes projetos de desenvolvimento de Software.

          ### 6. Example for a Solution Architect

          Ótimo profissional de análise e desenvolvimento de sistemas.
          Tem foco no resultado e na qualidade da entrega.

          ### 7. Example for a Solution Architect

          O Moisés é um profissional bastante focado, resiliente e preocupado em atender os prazos, propondo soluções que melhor se adequam à situação,
          visando sempre um equilíbrio entre as expectativas do cliente e a sustentabilidade do projeto.
          Trabalhei por alguns anos com ele e compartilhamos experiências que sempre agregavam nas soluções dos projetos.

  Junior Software Developer | LinkedIn recommendation:
    desc: A LinkedIn recommendation for a Junior Software Developer
    tags: [linkedin, recommendation, career]
    notes:
      - md: |
          ## 1. Template for a Junior Software Developer

          "[Name] quickly distinguished [himself/herself/themselves] at [Company] through [his/her/their] exceptional technical skills and eagerness to take on new challenges.
          Whether it was debugging complex software or creating user-friendly interfaces, [Name] handled it with finesse and professionalism.
          [He/she/they] would be an asset to any team."

          ## 2. Template for a Junior Software Developer

          "I thoroughly enjoyed my time working with [Name] at [Company], and came to know [him/her/them] as a truly valuable asset to any team.
          [He/she/they] is honest, dependable, and incredibly hard-working.
          Beyond that, [Name] is an impressive problem solver who is always able to address complex issues with strategy and confidence."

          ## 3. Template for a Junior Software Developer

          "[Name] has an amazing grasp on coding and development fundamentals, which [he/she/they] applied with great effect on the projects we worked on together.
          [His/her/their] contributions to our project were invaluable, showcasing [his/her/their] ability to not only work well under pressure but also to provide well-thought-out solutions to difficult problems."

          ## 4. Template for a Junior Software Developer

          "From the outset, [Name] impressed me with [his/her/their] ability to translate user requirements into actionable code that perfectly met our needs.
          [He/she/they] has always been an enthusiastic and innovative developer with a genuine passion for technology and learning."

          ## 5. Template for a Junior Software Developer

          "[Name] is a proactive and tireless contributor who would make a great addition to any team.
          During [his/her/their] time with us, [he/she/they] completed [specific project or task] with outstanding results and showed genuine dedication to not only meeting but exceeding expectations."

  Fullstack Engineer | LinkedIn recommendation:
    desc: A LinkedIn recommendation for a Fullstack Engineer
    tags: [linkedin, recommendation, career]
    notes:
      - md: |
          ## 1. Template for a Fullstack Engineer

          Working alongside Guilherme for over two years on a highly challenging project was an absolute privilege.
          As both his manager and friend, I've had a front-row seat to his exceptional talents as a full-stack developer.

          Guilherme's technical abilities are second to none.
          I often found that tasks that took me weeks, he'd master in days through sheer curiosity and lightning learning speed.
          His breadth of expertise spanning backend, frontend and mobile made him an invaluable swiss-army knife.

          More than just a technical expert, Guilherme elevates everyone around him.
          His dedication, passion, and vibrant personality make him not only a fantastic developer but also a transformative team player.
          While we didn't always see eye to eye, our discussions were always productive and enlightening, making him a delight to work with.

          Guilherme is a gem within any team, combining brilliant technical skills with a charismatic presence that inspires and motivates his colleagues.
          Any team would be fortunate to have him, and I cannot recommend him highly enough.

  Tech Lead | LinkedIn recommendation:
    desc: A LinkedIn recommendation for a Fullstack Engineer
    tags: [linkedin, recommendation, career]
    notes:
      - md: |
          ## 1. Template for a Tech Lead

          It was a distinct pleasure to lead and collaborate with Caciano for nearly two years on a demanding project—an app that achieved over a million downloads across both Play and App Stores.

          Starting as a third-party contractor, he quickly became indispensable, spearheading the migration of a complex Hybrid Mobile App to Flutter with outstanding quality and impressive results.

          Caciano's versatility and commitment shone brightly across all domains—be it backend, frontend, mobile, or even DevOps. His ability to rapidly master new languages and frameworks was nothing short of remarkable, exemplified by his proficiency with Flutter in just a few weeks.

          Beyond his technical skills, what truly sets Caciano apart is his exceptional ability to uplift everyone around him.
          His amiable personality, good-humored nudges, and big heart transformed even the most intense crunch times into enjoyable experiences.
          He inspired me to improve my own leadership through his relentless advocacy for quality and sustainable practices.

          Caciano is a gem of a find, blending brilliant technical acumen with a charismatic aura that motivates and inspires his colleagues.
          Any team would be lucky to have him. I recommend him enthusiastically and without any reservations.

          ## 2. Template for a Tech Lead

          I had the honour of working with Caciano for over two years on a highly challenging project, as not only a leader but a friend.

          What began as a third-party contract role quickly evolved as Caciano demonstrated his indispensable value.
          He spearheaded migrating our complex hybrid mobile app to Flutter, applying his technical mastery to deliver outstanding quality and results.

          Caciano's versatility and commitment shone brightly across all domains—be it backend, frontend, mobile, or even DevOps.
          His ability to rapidly master new languages and frameworks was nothing short of remarkable, exemplified by his proficiency with Flutter in just a few weeks.

          However, Caciano's greatest strengths extend well beyond his technical wizardry.
          No matter how stressful or daunting the situation, Caciano's positive energy and wonderful sense of humor lifted our spirits and fostered an enjoyable, collaborative environment.
          His passionate advocacy for sustainable processes inspired me to be a better leader.

          Caciano is that rare talent who combines world-class technical abilities with unparalleled emotional intelligence.
          Any organization would be fortunate to have such a gift, and I give my highest recommendation without reservation.

  Senior Software Engineer | LinkedIn recommendation:
    desc: A LinkedIn recommendation for a Senior Software Engineer
    tags: [linkedin, recommendation, career]
    notes:
      - md: |
          ## 1. Template for a Senior Software Engineer

          I have enjoyed working with [] for the last semester.
          Although we were in different teams, we had the opportunity to discuss about tecnical challenges, trends and solutions,
          from which I learned a lot. I was impressed with his knowledge and experience and no wonder how quickly he has become a reference in the company.
          His almost daily contributions have had a huge impact on the company's products, improving and tunning the code base and boosting the development process.
          As always an enthusiastic and innovative developer with a genuine passion for technology, he is someone who I will always look up to and follow his steps.
          If you have the chance to work with [NAME], take it!

          ## 2. Template for a Senior Software Engineer

          Moises is an exceptionally talented software engineer whom I've had the privilege of working alongside these past months.
          Though on different teams, our shared curiosity fostered many engaging discussions solving complex technical challenges with creativity and humor.

          His deep expertise shines through in the substantial improvements he's made optimizing and refactoring our codebase.
          Moises raises the bar for the entire team through his relentless pursuit of quality and innovative solutions.
          But what truly sets him apart is his eagerness share his knowledge always offering novel perspectives and thoughtful guidance.

          If you ever get the opportunity to work with Moises, I highly recommend seizing it.
          He is not only a remarkable asset to any team but also a pleasure to work alongside whom is in my first list when I am seeking advice or guidance.

          ## 3. Template for a Senior Software Engineer

          Moises is an exceptionally talented software engineer whom I've had the privilege of working alongside these past months.
          Though on different teams, our shared curiosity fostered many engaging discussions solving complex technical challenges with creativity and humor.

          His deep expertise shines through in the substantial improvements he's made optimizing and refactoring our codebase.
          Moises raises the bar for the entire team through his relentless pursuit of quality and innovative solutions quickly becoming a reference in the company.
          But what truly sets him apart is his eagerness to share his knowledge, always offering novel perspectives.

          If you ever get the opportunity to work with Moises, I highly recommend seizing it.
          He is not only a remarkable asset to any team but also a pleasure to collaborate with.

          Also, he tops my list when seeking advice or guidance.
