Suapina / Indiana -> Con / Zona Sul (Cidade Monsoes)

Persistent Systems | Multi-Nacional | USA/India | AWS/Azure

Agil?

0. Overall
1. Entrevista com recrutador da persistent
2. Direto ao ponto (seco)!
3. Transação em Dollar
4. Envia horas para 168/h
5. Demorado/Burocrático
6. Contrato (até 3 semanas)
1. Principais Stacks
3.1 Aprofundamento para essa stack
3.2 Situation/Problem
2. Gestor
1. Time
2. Equipe
3. Vender o seu peixe
4. Mostrar como se encaixa no time
