commands:
  brew install zoxide:
    desc: Install zoxide using homebrew | A smarter cd command for your terminal
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  z foo:
    desc: cd into highest ranked directory matching foo
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  z foo bar:
    desc: cd into highest ranked directory matching foo and bar
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  z foo /:
    desc: cd into a subdirectory starting with foo
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  z ~/foo:
    desc: z also works like a regular cd command
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  z foo/:
    desc: cd into relative path
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  z ..:
    desc: cd one level up
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  z -:
    desc: cd into previous directory
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  zi foo:
    desc: cd with interactive selection (using fzf)
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  z foo<SPACE><TAB>:
    desc: show interactive completions (zoxide v0.8.0+, bash 4.4+/fish/zsh only)
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  zoxide add ~/Work/node/demo:
    desc: Add or increment the rank of the directory "~/Work/node/demo"
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  zoxide edit:
    desc: Edit the database
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  zoxide import:
    desc: Import entries from another application
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  zoxide init:
    desc: Generate shell configuration
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  zoxide query -s -l:
    desc: List all directories in the database with their scores
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  zoxide query motion:
    desc: Search the database for directory matching "motion"
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  zoxide query motion -s:
    desc: Search the database for directory matching "motion" and shows its score
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
  zoxide remove:
    desc: Remove a directory from the database
    tags: [zsh, navigation]
    links:
      - https://github.com/ajeetdsouza/zoxide
      - https://youtu.be/aghxkpyRVDY
