require('etc/tables/compact')
require('etc/tables/concat')
require('etc/tables/each')
require('etc/tables/entries')
require('etc/tables/extend')
require('etc/tables/flat_entries')
require('etc/tables/flat_map')
require('etc/tables/flatten')
require('etc/tables/iter')
require('etc/tables/iterate_collection')
require('etc/tables/iterate')
require('etc/tables/join')
require('etc/tables/keys')
require('etc/tables/map')
require('etc/tables/merge')
require('etc/tables/push')
require('etc/tables/reduce')
return require('etc/tables/values')
