commands:
  npm i firebase-admin firebase-functions firebase-tools -D:
    desc: Add firebase dev deps
    tags: [firebase]
  npm i firebase:
    desc: Add firebase web deps
    tags: [firebase]
  npm install -g firebase-tools:
    desc: Install the Firebase CLI globally
    tags: [firebase]
  npx firebase login:
    desc: Log into Firebase - current Google account
    tags: [firebase]
  npx firebase login:ci:
    desc: Store token CI system as env var FIREBASE_TOKEN
    tags: [firebase]
  npx firebase projects:list:
    desc: List Firebase projects - current Google account
    tags: [firebase]
  npx firebase init:
    desc: Initialize a Firebase project
    tags: [firebase]
  npx firebase use --add <ALIAS>:
    desc: Add project ALIAS to .firebaserc
    tags: [firebase]
  npx firebase use:
    desc: List aliases for current project
    tags: [firebase]
  npx firebase use <ALIAS>:
    desc: Setup Firebase to use a project
    tags: [firebase]
  npx firebase use --clear:
    desc: Clear active project
    tags: [firebase]
  npx firebase init hosting:
    desc: Setup Firebase Hosting
    tags: [firebase]
  npx firebase init hosting:github:
    desc: Setup GH Actions to deploy to Firebase Hosting
    tags: [firebase]
  npx firebase init functions:
    desc: Create Cloud Functions project
    tags: [firebase]
  npx firebase init emulators:
    desc: Setup the Emulator Suite
    tags: [firebase]
  npx firebase emulators:start:
    desc: Start Emulator Suite
    tags: [firebase]
  npx firebase emulators:start --only functions:
    desc: Start Emulator Suite (ONLY FUNCTIONS)
    tags: [firebase]
  npx firebase emulators:start --only hosting:
    desc: Start Emulator Suite (ONLY HOSTING)
    tags: [firebase]
  npx firebase deploy --only functions:
    desc: Deploy firebase functions
    tags: [firebase]
  npx firebase deploy --only hosting:
    desc: Deploy firebase hostings
    tags: [firebase]
  npx firebase deploy:
    desc: Deploy to Firebase
    tags: [firebase]
  npx firebase hosting:channel:list:
    desc: List channels - including 'live' - from default Hosting
    tags: [firebase]
  npx firebase hosting:channel:create <ID>:
    desc: Create prev channel ID
    tags: [firebase]
  npx firebase hosting:channel:open <ID>:
    desc: Open or returns channel ID URL
    tags: [firebase]
  npx firebase hosting:channel:deploy <ID>:
    desc: Deploy prev channel to HOST - expires in 7d
    tags: [firebase]
  npx firebase hosting:channel:delete <ID>:
    desc: Delete prev channel
    tags: [firebase]
