-- -- ~/.config/nvim/lua/config/lualine.lua
-- -- or add this to your LazyVim plugins configuration

-- return {
--   "nvim-lualine/lualine.nvim",
--   opts = function(_, opts)
--     -- Custom theme colors to match your dark theme
--     local colors = {
--       bg = '#2d3748',
--       fg = '#a0aec0',
--       yellow = '#f6e05e',
--       cyan = '#4fd1c7',
--       darkblue = '#2d3748',
--       green = '#68d391',
--       orange = '#ed8936',
--       violet = '#9f7aea',
--       magenta = '#ed64a6',
--       blue = '#4299e1',
--       red = '#f56565',
--     }

--     local custom_theme = {
--       normal = {
--         a = { fg = colors.bg, bg = colors.green },
--         b = { fg = colors.fg, bg = colors.bg },
--         c = { fg = colors.fg, bg = colors.bg },
--       },
--       insert = {
--         a = { fg = colors.bg, bg = colors.blue },
--         b = { fg = colors.fg, bg = colors.bg },
--         c = { fg = colors.fg, bg = colors.bg },
--       },
--       visual = {
--         a = { fg = colors.bg, bg = colors.magenta },
--         b = { fg = colors.fg, bg = colors.bg },
--         c = { fg = colors.fg, bg = colors.bg },
--       },
--       replace = {
--         a = { fg = colors.bg, bg = colors.red },
--         b = { fg = colors.fg, bg = colors.bg },
--         c = { fg = colors.fg, bg = colors.bg },
--       },
--       command = {
--         a = { fg = colors.bg, bg = colors.yellow },
--         b = { fg = colors.fg, bg = colors.bg },
--         c = { fg = colors.fg, bg = colors.bg },
--       },
--       inactive = {
--         a = { fg = colors.fg, bg = colors.bg },
--         b = { fg = colors.fg, bg = colors.bg },
--         c = { fg = colors.fg, bg = colors.bg },
--       },
--     }

--     -- Override the default configuration
--     opts.options = {
--       theme = custom_theme,
--       component_separators = { left = '', right = '' },
--       section_separators = { left = '', right = '' },
--       globalstatus = true,
--       refresh = {
--         statusline = 1000,
--         tabline = 1000,
--         winbar = 1000,
--       },
--     }

--     opts.sections = {
--       lualine_a = {},
--       lualine_b = {
--         {
--           'branch',
--           icon = '',
--           color = { fg = colors.green },
--         },
--         {
--           'diff',
--           symbols = { added = ' ', modified = ' ', removed = ' ' },
--           diff_color = {
--             added = { fg = colors.green },
--             modified = { fg = colors.orange },
--             removed = { fg = colors.red },
--           },
--         },
--       },
--       lualine_c = {
--         {
--           'filename',
--           file_status = true,
--           newfile_status = false,
--           path = 1, -- 0: Just the filename, 1: Relative path, 2: Absolute path, 3: Absolute path with ~ for home
--           shorting_target = 40,
--           symbols = {
--             modified = ' ●',
--             readonly = ' ',
--             unnamed = '[No Name]',
--             newfile = '[New]',
--           },
--           color = { fg = colors.fg },
--         },
--       },
--       lualine_x = {
--         {
--           'diagnostics',
--           sources = { 'nvim_diagnostic' },
--           symbols = { error = 'e', warn = 'w', info = 'i', hint = 'h' },
--           diagnostics_color = {
--             error = { fg = colors.red },
--             warn = { fg = colors.yellow },
--             info = { fg = colors.cyan },
--             hint = { fg = colors.blue },
--           },
--           colored = true,
--           update_in_insert = false,
--           always_visible = false,
--         },
--         {
--           function()
--             local msg = 'No Active Lsp'
--             local buf_ft = vim.api.nvim_buf_get_option(0, 'filetype')
--             local clients = vim.lsp.get_active_clients()
--             if next(clients) == nil then
--               return msg
--             end
--             for _, client in ipairs(clients) do
--               local filetypes = client.config.filetypes
--               if filetypes and vim.fn.index(filetypes, buf_ft) ~= -1 then
--                 return client.name
--               end
--             end
--             return msg
--           end,
--           icon = '',
--           color = { fg = colors.cyan },
--         },
--       },
--       lualine_y = {
--         {
--           'progress',
--           color = { fg = colors.fg },
--         },
--       },
--       lualine_z = {
--         {
--           'location',
--           color = { fg = colors.fg },
--         },
--       },
--     }

--     opts.inactive_sections = {
--       lualine_a = {},
--       lualine_b = {},
--       lualine_c = { 'filename' },
--       lualine_x = { 'location' },
--       lualine_y = {},
--       lualine_z = {},
--     }

--     return opts
--   end,
-- }

return {
  -- only show the first character of the mode
  mode = { 'mode', fmt = function(str) return str:sub(1, 1) end }
}
