#!/bin/bash

declare -a PACKAGES=(
  curl
)

is_exec() {
  type "$1" > /dev/null 2>&1
}

add_package() {
  case "$OSTYPE" in
    *darwin*) brew install "$1" ;;
    *linux-musl*) sudo apk add "$1" ;;
    *linux-gnu*) sudo apt-get install --yes "$1" ;;
    *) echo "$OSTYPE not handled! Skipping.." ;;
  esac
}

for package in "${PACKAGES[@]}"; do
  if ! is_exec "$package"; then
    add_package "$package"
  fi
done
