#!/usr/bin/env bash
# shellcheck shell=bash disable=SC2154,SC2155,SC2034

#? psc 0.1.0
#? License RIT (Robot Institute of Technology)
#? This is free software: you are free to change and redistribute it.
#? There is NO WARRANTY, to the extent permitted by law.
#? http://docopt.org · Command-line interface description language
#? https://gopass.pw · Password manager

##? Copies the pass|gopass 'key' value to clipboard
##?
##? Usage:
##?      psc [KEY] [ options ]
##?
##? Options:
##?     -h, --help            Show this screen.
##?
##? Examples:
##?     psc
##?     psc tools/bitly.com/token

psc() {
    local -A opts

    # Parse options into opts associative array
    # -D: remove parsed flags from $@
    # -F: fail on unknown flags
    # -E: stop at first non-option
    # -A: store results in associative array
    zparseopts -D -F -E -A opts \
        h=help -help=help

    # Example usage of parsed options
    if (( ${+opts[-h]} )) || (( ${+opts[--help]} )); then
      autoload -Uz show_usage
      show_usage
      return 0
    fi

  if [[ -z "$1" ]]; then
    local it="$(gopass ls --flat | gum filter --limit=1)"
    if [[ -n "$it" ]]; then
      psc "$it"
    fi
    return 0;
  fi

  gopass show --clip "$1";
}

psc "$@"

# vi: set ft=sh:
