# https://taskfile.dev/usage/
version: '3'

env:
  VIM_PATH: '{{.VIM_PATH}}'
  VIM_PATH_LUA: '{{.VIM_PATH}}/lua'

tasks:
  build:
    dir: '$VIM_PATH'
    desc: Compiles src/**/*.yue into lua/**/*.lua
    cmds:
      - yue -t lua/ ./src
    sources:
      - src/**/*.yue

  lint:
    dir: '$VIM_PATH'
    desc: Lints lua files
    cmds:
      - luacheck --config=.luacheckrc {*.lua,lua/**/*.lua} --exclude-files={src,specs,plugin}/*

  format:
    dir: '$VIM_PATH'
    desc: Reformats Lua source code
    cmds:
      - lua-format --config=.lua-format.yml --in-place=lua/**/*.lua

  test:
    dir: '$VIM_PATH'
    desc: Runs lua tess at specs folder
    cmds:
      - busted --keep-going --recursive --config-file=.busted --helper=specs/tools/spec_helper.lua
