# MISE GLOBAL CONFIG FILE
# https://mise.jdx.dev/configuration.html#global-config-config-mise-config-toml

[settings]
# https://mise.jdx.dev/configuration/settings.html
# tools can read the versions files used by other version managers

# configure `mise install` to always keep the downloaded archive
always_keep_download = false  # deleted after install by default
always_keep_install = false  # deleted on failure by default

# Enable color output in the terminal
# https://mise.jdx.dev/configuration/settings.html#color
color = true  # set to true to enable color output

# Set the color theme for the terminal output: default |charm | base16 | catppuccin | dracula
# https://mise.jdx.dev/configuration/settings.html#color_theme
color_theme = "dracula"

# set to true to expand environment variables in the shell for example:
#   [env]
#   FOO = "hello"
#   BAR = "$FOO-world"          # "hello-world"
#   BAZ = "${FOO}_suffix"       # "hello_suffix"
#   QUX = "${UNDEF:-fallback}"  # "fallback"
# https://mise.jdx.dev/configuration/settings.html#env_shell_expand
# env_shell_expand = true

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdx/mise/discussions/6735)
plugin_autoupdate_last_check_duration = "1 week"  # set to 0 to disable updates

# config files with these prefixes will be trusted by default
# https://mise.jdx.dev/configuration/settings.html#trusted_config_paths
trusted_config_paths = [
  "~/config",
  "~/config/mise",
  "~/Work/dots/config/mise",
  "~/.local/share/dots",
  "~/.local/share/dots/config",
  "~/.local/share/dots/config/mise",
]

verbose = false  # set to true to see full installation output, see `MISE_VERBOSE`
http_timeout = "30s"  # set the timeout for http requests as duration string, see `MISE_HTTP_TIMEOUT`
jobs = 4  # number of plugins or runtimes to install in parallel. The default is `4`.
raw = false  # set to true to directly pipe plugins to stdin/stdout/stderr
yes = false  # set to true to automatically answer yes to all prompts

# Automatically install missing tools when running mise x, mise run, or as part of the 'not found' handler.
# https://mise.jdx.dev/configuration/settings.html#auto_install
auto_install = true

# Automatically install missing tools when running mise x, mise run, or as part of the 'not found' handler.
# https://mise.jdx.dev/configuration/settings.html#not_found_auto_install
not_found_auto_install = true

# Set the package manager for npm: npm | bun | pnpm
# https://mise.jdx.dev/configuration/settings.html#npm_package_manager
# npm.package_manager = "bun"

# paranoid = false       # see MISE_PARANOID
# shorthands_file = '~/.config/mise/shorthands.toml' # path to the shorthands file, see `MISE_SHORTHANDS_FILE`
# disable_default_shorthands = false # disable the default shorthands, see `MISE_DISABLE_DEFAULT_SHORTHANDS`
# disable_tools = ['node']           # disable specific tools, generally used to turn off core tools
# env_file = '.env' # load env vars from a dotenv file, see `MISE_ENV_FILE`

# Enables experimental features
# https://mise.jdx.dev/configuration/settings.html#experimental
experimental = true

# By default, idiomatic version files are disabled
# for example, .nvmrc in the case of node's nvm
# https://mise.jdx.dev/configuration/settings.html#idiomatic_version_file_enable_tools
# https://mise.jdx.dev/configuration.html#idiomatic-version-files
idiomatic_version_file_enable_tools = [
  "go",
  "node",
  "java",
  "python",
  "ruby",
  "yarn"
]

# The Tera template method for defining task arguments is deprecated and will be removed in mise 2026.11.0.
# This disable the two-pass parsing behavior immediately
# https://mise.jdx.dev/configuration/settings.html#task.disable_spec_from_run_scripts
# Instead use https://usage.jdx.dev/spec
task.disable_spec_from_run_scripts = true

# Change output style when executing tasks: keep-order | prefix | interleave | replacing | timed | quiet | silent
# This controls the output of mise run. (see Tasks Runner for more)
# https://mise.jdx.dev/configuration/settings.html#task_output
task_output = "quiet"  # stream one task's output live while buffering others, printing in definition order as tasks complete

[tools]
watchexec = "latest"
usage = "latest"

# Show the full command when executing tasks.
# https://mise.jdx.dev/configuration/settings.html#task.show_full_cmd
# task.show_full_cmd = "disable_spec_from_run_scripts"

# # configure messages displayed when entering directories with config files
# status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
