# https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
# https://docs.docker.com/build/ci/github-actions/test-before-push
name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: 'dots-${{ github.ref }}'

defaults:
  run:
    shell: bash

env:
  CI: true
  FORCE_COLOR: true
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1
  REGISTRY_IMAGE: ${{ github.repository }}

jobs:
  lint:
    runs-on: ${{ matrix.runner }}
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        distro: [debian, ubuntu]
        include:
          - distro: debian
            runner: ubuntu-latest
          - distro: ubuntu
            runner: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: distros/${{ matrix.distro }}/Dockerfile
          config: ./.hadolint.yaml
  validate:
    runs-on: ${{ matrix.runner }}
    needs: lint
    strategy:
      matrix:
        distro: [debian, ubuntu]
        include:
          - distro: debian
            runner: ubuntu-latest
          - distro: ubuntu
            runner: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      checks: write
    outputs:
      DISTRO: ${{ matrix.distro }}
      SHORT_SHA: ${{ steps.setup.outputs.SHORT_SHA }}
      IMAGE_NAME: ${{ steps.setup.outputs.IMAGE_NAME }}
      REGISTRY_URL_TAGS: ${{ steps.setup.outputs.REGISTRY_URL_TAGS }}
      REGISTRY_URL: ${{ steps.setup.outputs.REGISTRY_URL }}
      IMAGE_INFO: ${{ steps.setup.outputs.IMAGE_INFO }}
    steps:
      - name: Setup outputs
        id: setup
        run: |
          short_sha=$(echo $GITHUB_SHA | cut -c1-7)
          registry_url_tags=https://hub.docker.com/r/${{ env.REGISTRY_IMAGE }}/tags
          echo "DISTRO=${{ matrix.distro }}" >> $GITHUB_OUTPUT
          echo "SHORT_SHA=$short_sha" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=${{ env.REGISTRY_IMAGE }}:${{ matrix.distro }}-pr-${{ github.event.pull_request.number }}-${short_sha}" >> $GITHUB_OUTPUT
          echo "REGISTRY_URL_TAGS=${registry_url_tags}" >> $GITHUB_OUTPUT
          echo "REGISTRY_URL=${registry_url_tags}?name=pr-${{ github.event.pull_request.number }}-${short_sha}" >> $GITHUB_OUTPUT
        env:
          GITHUB_SHA: ${{ github.sha }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: roalcantara
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          target: remote
          build-args: BRANCH=${{ github.head_ref || github.ref_name }}
          file: distros/${{ matrix.distro }}/Dockerfile
          platforms: linux/amd64
          load: true
          push: false
          tags: ${{ steps.setup.outputs.IMAGE_NAME }}-amd64
          github-token: ${{ secrets.GH_TOKEN }}
          secrets: github_token=${{ secrets.GH_TOKEN }}
      - name: Run Container Structure Test (${{ matrix.distro }}/amd64)
        uses: docker://gcr.io/gcp-runtimes/container-structure-test:latest
        with:
          args: test -v debug --force --output junit --test-report cst_junit_report.xml --config distros/${{ matrix.distro }}/container-structure-test.yml --image ${{ steps.setup.outputs.IMAGE_NAME }}-amd64
      - name: Upload Test Report
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: cst_junit_report.xml
          check_name: Container Structure Tests (${{ matrix.distro }}/amd64)
