name: Publish

on:
  release:
    types: [published]

concurrency:
  cancel-in-progress: true
  group: 'dots-${{ github.ref }}'

env:
  CI: true
  FORCE_COLOR: true
  DOCKER_BUILDKIT: 1
  BUILDKIT_INLINE_CACHE: 1
  REGISTRY_IMAGE: ${{ github.repository }}

defaults:
  run:
    shell: bash

jobs:
  build-push:
    name: Build and Push Latest Images
    runs-on: ${{ matrix.image }}
    permissions:
      contents: read
      packages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.setup.outputs.REGISTRY_URL }}
    strategy:
      matrix:
        distro: [debian]
        include:
          - distro: debian
            image: ubuntu-latest
    steps:
      - name: Setup outputs
        id: setup
        run: |
          version=${GITHUB_REF#refs/tags/}
          version=${version#v}
          echo "VERSION=${version}" >> $GITHUB_OUTPUT
          echo "REGISTRY_URL=https://hub.docker.com/r/${{ env.REGISTRY_IMAGE }}/tags?name=${{ matrix.distro }}-${version}" >> $GITHUB_OUTPUT
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: roalcantara
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{ matrix.distro }}-latest
            type=semver,pattern=${{ matrix.distro }}-{{version}}
            type=semver,pattern=${{ matrix.distro }}-{{major}}.{{minor}}
            type=semver,pattern=${{ matrix.distro }}-{{major}}
            type=sha
      - name: Multi-platform Build and Push for ${{ matrix.distro }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          target: remote
          file: distros/${{ matrix.distro }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          sbom: true
          push: true
          # TODO: Enable provenance when we have a way to sign the images
          provenance: false
          cache-from: |
            type=gha,scope=build-${{ matrix.distro }}-amd64
            type=gha,scope=build-${{ matrix.distro }}-arm64
            type=registry,ref=docker.io/${{ env.REGISTRY_IMAGE }}-cache:${{ matrix.distro }}
          cache-to: |
            type=gha,scope=build-${{ matrix.distro }}-amd64,mode=max
            type=gha,scope=build-${{ matrix.distro }}-arm64,mode=max
            type=registry,ref=docker.io/${{ env.REGISTRY_IMAGE }}-cache:${{ matrix.distro }},mode=max
          github-token: ${{ secrets.GH_TOKEN }}
          secrets: GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
